import type { Metadata } from "next";
import {Lato, IM_Fell_English_SC} from "next/font/google";
import "./globals.css";


const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: "100"
});

const fell = IM_Fell_English_SC({
  variable: "--font-fell",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fell.variable} ${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
